NS Contacts:
  source: API
  type: internal
  privacy: public
  columns:
    - name: Currency
      source_name: cur_code
    - name: URL
      source_name: url
    - name: Facebook
      source_name: facebook
    - name: Twitter
      source_name: twitter
    - name: Other social
      source_name: othersocial

FDRS:
  Source: API
  type: internal
  privacy: public
  Link: https://data.ifrc.org/fdrs
  Focal point: Rania Alerksoussi
  indicators:
    - name: Number of local units
      source_name: KPI_noLocalUnits
    - name: Financial statement available
      source_name: KPI_hasFinancialStatement
    - name: Audited financial statement available
      source_name: audited
    - name: Total income in local currency
      source_name: KPI_IncomeLC
    - name: Total income (Swiss Franc)
      source_name: KPI_IncomeLC_CHF
    - name: Total number of people volunteering
      source_name: KPI_PeopleVol_Tot
    - name: Total number of volunteers covered by accident insurance
      source_name: KPI_noVolCoveredAI_Tot
    - name: Total number of paid staff
      source_name: KPI_PStaff_Tot
    - name: Total number of paid staff covered by accident insurance
      source_name: KPI_PStaffCoveredAI_Tot
    - name: Annual report available
      source_name: ar
    - name: Strategic plan available
      source_name: sp
    - name: Supported NSs
      source_name: supported1
    - name: Received support from NSs
      source_name: received_support1
    - name: Total number of people reached by disaster response and early recovery programmes
      source_name: KPI_ReachDRER_CPD
    - name: Total number of people reached by long term services and development programmes
      source_name: KPI_ReachLTSPD_CPD
    - name: Total number of people reached by disaster risk reduction
      source_name: KPI_ReachDRR_CPD
    - name: Total number of people reached by shelter
      source_name: KPI_ReachS_CPD
    - name: Total number of people reached by livelihoods
      source_name: KPI_ReachL_CPD
    - name: Total number of people reached by health
      source_name: KPI_ReachH_CPD
    - name: Total number of people reached by water, sanitation and hygiene
      source_name: KPI_ReachWASH_CPD
    - name: Total number of people reached by migration
      source_name: KPI_ReachM_CPD
    - name: Total number of people reached by cash transfer programming
      source_name: KPI_ReachCTP_CPD
    - name: Total number of people reached by social inclusion and building a culture of non-violence and peace
      source_name: KPI_ReachSI_CPD
    - name: Year of latest financial statement
      source_name: Year of latest financial statement
    - name: Year of latest audited financial statement
      source_name: Year of latest audited financial statement
    - name: Year of latest annual report
      source_name: Year of latest annual report
    - name: Year of latest strategic plan
      source_name: Year of latest strategic plan

NS Documents:
  Source: API
  type: internal
  privacy: public
  link: https://data.ifrc.org/fdrs
  indicators:
  - name: Annual report
    source_name: Our Annual Report
  - name: Financial statement (audited)
    source_name: Our Audited Financial Statements
  - name: Strategic Plan
    source_name: Our Strategic Plan
  - name: Financial statement (unaudited)
    source_name: Our Unaudited Financial Statement
  - name: Red Cross law
    source_name: Our Red Cross Law
  - name: Statutes in force
    source_name: Our Statutes in Force
  - name: Emblem law
    source_name: Our Emblem Law

OCAC:
  Source: file
  Type: Internal
  privacy: confidential
  Link: https://data-api.ifrc.org/Backoffice/OCAC/Form?app=ocac
  Focal point: Roger Fischli

OCAC Assessment Dates:
  Source: file
  Type: Internal
  privacy: public
  Link: https://data-api.ifrc.org/Backoffice/OCAC/Form?app=ocac
  Focal point: Roger Fischli

Statutes:
  Source: file
  Type: Internal
  privacy: confidential
  Focal point: Drina Karahasanovic

Recognition Laws:
  Source: file
  privacy: confidential
  Type: Internal
  Focal point: Drina Karahasanovic
  columns:
    - name: NS recognition laws/ other regulations in force
      source_name: Law/other regulations in force

YABC:
  source: file
  source_description: IFRC Youth
  Type: Internal
  privacy: confidential
  Focal point: Amjad Saleem
  columns:
    - name: Number of YABC trainings to date
      source_name: number of YABC trainings to date
    - name: Number of peer educators
      source_name: peer educators
    - name: Number of trainers
      source_name: trainers
    - name: Comment
      source_name: Comment

Logistics Projects:
  source: file
  source_description: IFRC Logistics
  Type: Internal
  privacy: confidential
  Focal point: Juan Galvez

GO Operations:
  source: API
  source_description: IFRC GO
  Type: Internal
  Link: https://go.ifrc.org/
  privacy: public
  Focal point: Luke Caley
  columns:
    - name: Operation name
      source_name: name
    - name: Type
      source_name: atype_display
    - name: Number of beneficiaries
      source_name: num_beneficiaries
    - name: Requested amount
      source_name: amount_requested
    - name: Funded amount
      source_name: amount_funded
    - name: Disaster type
      source_name: dtype.name
    - name: Funding
      source_name: funding

GO Projects:
  source: API
  source_description: IFRC GO
  Type: Internal
  privacy: public
  Link: https://go.ifrc.org/three-w/
  Focal point: Luke Caley
  columns:
    - name: Project name
      source_name: name
    - name: Disaster type
      source_name: dtype_detail.name
    - name: Event description
      source_name: event_detail.name
    - name: Sector
      source_name: primary_sector_display
    - name: Programme type
      source_name: programme_type_display
    - name: Operation type
      source_name: operation_type_display
    - name: Start date
      source_name: start_date
    - name: End date
      source_name: end_date
    - name: Budget amount
      source_name: budget_amount
    - name: Actual expenditure
      source_name: actual_expenditure
    - name: Target total
      source_name: target_total
    - name: Reached total
      source_name: reached_total

World Development Indicators:
  source: API
  privacy: public
  source_description: WorldBank World Development Indicators
  Type: External
  Link: https://databank.worldbank.org/source/world-development-indicators
  indicators:
    - name: Population, total
      source_name: SP.POP.TOTL
    - name: GDP (US dollars)
      source_name: NY.GDP.MKTP.CD
    - name: Poverty headcount ratio at national poverty lines (% of population)
      source_name: SI.POV.NAHC
    - name: GNI per capita, Atlas method (current US$)
      source_name: NY.GNP.PCAP.CD
    - name: Life expectancy at birth, total years
      source_name: SP.DYN.LE00.IN
    - name: Literacy rate, adult total (% of people ages 15 and above)
      source_name: SE.ADT.LITR.ZS
    - name: Urban population (% of total)
      source_name: SP.URB.TOTL.IN.ZS

UNDP Human Development:
  source: API
  privacy: public
  source_description: UNDP
  Type: External
  Link: https://hdr.undp.org/en/content/human-development-index-hdi
  indicators:
    - name: Human Development Index (HDI)
      source_name: 137506

INFORM Risk:
  source: API
  privacy: public
  source_description: EC DRMKC INFORM
  Type: External
  Link: https://drmkc.jrc.ec.europa.eu/inform-index/INFORM-Risk
  indicators:
    - name: INFORM Risk Index
      source_name: INFORM

ICRC Presence:
  source: website
  privacy: public
  source_description: ICRC presence
  Type: External
  Link: https://www.icrc.org/en/where-we-work
  Columns:
    - name: ICRC presence
      source_name: ICRC presence
    - name: Key operation
      source_name: Key operation
    - name: URL
      source_name: URL
    - name: Description
      source_name: Description

IFRC Disaster Law:
  source: website
  privacy: public
  source_description: IFRC disaster law information
  Type: External
  Link: https://disasterlaw.ifrc.org/where-we-work
  Columns:
    - name: ID
      source_name: ID
    - name: URL
      source_name: URL
    - name: Description
      source_name: Description

Corruption Perception Index:
  source: website
  privacy: public
  source_description: Transparency International (TI) Corruption Perception Index (CPI)
  type: external
  link: https://www.transparency.org/en/
  columns:
    - name: Score
      source_name: score
    - name: Rank
      source_name: rank
    - name: Sources
      source_name: sources
    - name: Standard error
      source_name: standardError
    - name: Year
      source_name: year

Youth Engagement:
  source: website
  privacy: public
  source_description: IFRC Youth engagement global survey.
  type: internal
  link: https://volunteeringredcross.org/en/global-youth-survey-en/
  columns:
    - name: Year
      source_name: Year
    - name: Youth Policy
      source_name: Youth Policy
    - name: Youth Engagement Strategy
      source_name: Youth Engagement Strategy
    - name: Youth in GB
      source_name: Youth in GB
    - name: Youth-led structure
      source_name: Youth-led structure