NS Contacts:
  source: API
  type: internal
  privacy: public

Evaluations:
  source: website
  privacy: public
  source_description: IFRC evaluations
  type: external
  link: https://www.ifrc.org/evaluations

FDRS:
  source: API
  type: internal
  privacy: public
  link: https://data.ifrc.org/fdrs
  focal point: Rania Alerksoussi

NS Documents:
  source: API
  type: internal
  privacy: public
  link: https://data.ifrc.org/fdrs

OCAC:
  source: file
  type: Internal
  privacy: confidential
  link: https://data-api.ifrc.org/Backoffice/OCAC/Form?app=ocac
  focal point: Roger Fischli

OCAC Assessment Dates:
  source: API
  source_description: NS databank
  type: Internal
  privacy: public
  link: https://data-api.ifrc.org/Backoffice/OCAC/Form?app=ocac
  focal point: Roger Fischli

BOCA Assessment Dates:
  source: API
  source_description: NS databank
  type: Internal
  privacy: public
  link: https://data-api.ifrc.org/Backoffice/BOCA/Form?app=boca
  focal point: Roger Fischli

Statutes:
  source: file
  type: Internal
  privacy: confidential
  focal point: Drina Karahasanovic

Recognition Laws:
  source: file
  privacy: confidential
  type: Internal
  focal point: Drina Karahasanovic

YABC:
  source: file
  source_description: IFRC Youth
  type: Internal
  privacy: confidential
  focal point: Amjad Saleem

Logistics Projects:
  source: file
  source_description: IFRC Logistics
  type: Internal
  privacy: confidential
  focal point: Juan Galvez

GO Operations:
  source: API
  source_description: IFRC GO
  type: Internal
  link: https://go.ifrc.org/
  privacy: public
  focal point: Luke Caley

GO Projects:
  source: API
  source_description: IFRC GO
  type: Internal
  privacy: public
  link: https://go.ifrc.org/three-w/
  focal point: Luke Caley

World Development Indicators:
  source: API
  privacy: public
  source_description: WorldBank World Development Indicators
  type: External
  link: https://databank.worldbank.org/source/world-development-indicators

UNDP Human Development:
  source: API
  privacy: public
  source_description: UNDP
  type: External
  link: https://hdr.undp.org/en/content/human-development-index-hdi

INFORM Risk:
  source: API
  privacy: public
  source_description: EC DRMKC INFORM
  type: External
  link: https://drmkc.jrc.ec.europa.eu/inform-index/INFORM-Risk

ICRC Presence:
  source: website
  privacy: public
  source_description: ICRC presence
  type: External
  link: https://www.icrc.org/en/where-we-work

IFRC Disaster Law:
  source: website
  privacy: public
  source_description: IFRC disaster law information
  type: External
  link: https://disasterlaw.ifrc.org/where-we-work

Corruption Perception Index:
  source: website
  privacy: public
  source_description: Transparency International (TI) Corruption Perception Index (CPI)
  type: external
  link: https://www.transparency.org/en/

Youth Engagement:
  source: website
  privacy: public
  source_description: IFRC Youth engagement global survey.
  type: internal
  link: https://volunteeringredcross.org/en/global-youth-survey-en/
